# Generated by Django 6.0.3 on 2026-07-18 09:57

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, validators=[profiles.models.validate_birth_date]
            ),
        ),
    ]
