# Generated by Django 6.0.3 on 2026-07-18 11:14

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=profiles.models.random_default_avatar,
                null=True,
                upload_to=profiles.models.user_avatar_path,
                validators=[
                    profiles.models.validate_image_size,
                    profiles.models.validate_image_dimensions,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                ],
            ),
        ),
    ]
