# Generated by Django 6.0.7 on 2026-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_is_email_verified_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
