# Generated by Django 6.0.3 on 2026-07-18 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره موبایل باید با 09 شروع شود و 11 رقم باشد.",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
    ]
