# Generated by Django 6.0.7 on 2026-09-28 08:30

import django.core.validators
import django_ckeditor_5.fields
import pages.utils
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="اگر اسلاگ را خالی بگذارید، از روی همین ساخته می\u200cشود.",
                        max_length=200,
                        verbose_name="عنوان انگلیسی",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="فقط حروف انگلیسی، عدد و خط تیره. خالی بگذارید تا از عنوان انگلیسی ساخته شود. تغییر بعد از انتشار، لینک قبلی صفحه را از کار می\u200cاندازد.",
                        max_length=150,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="محتوا"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "show_in_menu",
                    models.BooleanField(default=False, verbose_name="نمایش در منو"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="نمایش در فوتر"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="اگر خالی بماند، خودکار از ابتدای محتوا ساخته می\u200cشود.",
                        max_length=160,
                        verbose_name="توضیحات سئو",
                    ),
                ),
                (
                    "include_in_sitemap",
                    models.BooleanField(default=True, verbose_name="عضویت در sitemap"),
                ),
            ],
            options={
                "verbose_name": "صفحه ثابت",
                "verbose_name_plural": "صفحات ثابت",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="عنوان"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="مثال: /products/ یا https://example.com — اگر خالی باشد اسلاید لینک ندارد.",
                        max_length=500,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="لینک باید با / (مسیر داخلی) یا http:// و https:// شروع شود.",
                                regex="^(/|https?://)",
                            )
                        ],
                        verbose_name="لینک",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="به\u200cصورت خودکار به اندازه\u200cی SLIDER_DESKTOP_SIZE (پیش\u200cفرض ۱۹۲۰×۷۰۰) کراپ می\u200cشود.",
                        upload_to=pages.utils.slide_desktop_upload_path,
                        validators=[
                            products.validators.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                        verbose_name="تصویر دسکتاپ",
                    ),
                ),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="اختیاری؛ به اندازه\u200cی SLIDER_MOBILE_SIZE (پیش\u200cفرض ۸۰۰×۸۰۰) کراپ می\u200cشود. اگر خالی باشد، تصویر دسکتاپ استفاده می\u200cشود.",
                        null=True,
                        upload_to=pages.utils.slide_mobile_upload_path,
                        validators=[
                            products.validators.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                        ],
                        verbose_name="تصویر موبایل",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="متن جایگزین تصویر (alt)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچک\u200cتر، زودتر نمایش داده می\u200cشود.",
                        verbose_name="ترتیب",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی = از همین حالا",
                        null=True,
                        verbose_name="شروع نمایش",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی = بدون پایان",
                        null=True,
                        verbose_name="پایان نمایش",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلایدهای صفحه اصلی",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_at", "end_at"],
                        name="pages_slide_is_acti_98ab53_idx",
                    )
                ],
            },
        ),
    ]
