# Generated by Django 6.0.7 on 2026-09-28 08:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="template_name",
            field=models.CharField(
                blank=True,
                help_text="خالی = قالب پیش\u200cفرض. قالب\u200cهای اختصاصی از پوشه\u200cی templates/pages/custom/ خوانده می\u200cشوند.",
                max_length=150,
                verbose_name="قالب اختصاصی",
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="برای صفحه\u200cی قالب\u200cدار اختیاری است؛ برای قالب پیش\u200cفرض الزامی است.",
                verbose_name="محتوا",
            ),
        ),
    ]
