# Generated by Django 6.0.7 on 2026-09-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcategory",
            options={
                "ordering": ["title"],
                "verbose_name": "دسته\u200cی وبلاگ",
                "verbose_name_plural": "دسته\u200cهای وبلاگ",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["title"]},
        ),
    ]
