# Generated by Django 6.0.7 on 2026-09-26 08:25

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_postcategory_options_alter_tag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image_jpg",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="نسخه\u200cی خودکار JPG از cover_image، مخصوص og:image (چون تلگرام webp را در پیش\u200cنمایش لینک نشان نمی\u200cدهد).",
                null=True,
                upload_to=blog.utils.blog_cover_jpg_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="عنوان انگلیسی؛ در صورت پر بودن، اسلاگ از روی همین ساخته می\u200cشود (توصیه\u200cی اکید: همیشه پر شود).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="عنوان انگلیسی؛ در صورت پر بودن، اسلاگ از روی همین ساخته می\u200cشود.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_en",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.utils.blog_cover_upload_path
            ),
        ),
    ]
