# Generated by Django 6.0.7 on 2026-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_cover_image_jpg_post_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="guest_name",
            field=models.CharField(
                blank=True,
                help_text="برای مهمان الزامی است؛ برای کاربر لاگین\u200cشده فقط وقتی در پروفایلش نامی ثبت نشده باشد، از همین استفاده می\u200cشود.",
                max_length=100,
            ),
        ),
    ]
