# Generated by Django 6.0.7 on 2026-08-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0004_product_products_pr_sales_c_6796bf_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("processing", "در حال پردازش"),
                            ("shipped", "ارسال شده"),
                            ("delivered", "تحویل داده شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("address_title", models.CharField(blank=True, max_length=100)),
                ("address_full_text", models.TextField()),
                ("address_postal_code", models.CharField(max_length=10)),
                ("address_receiver_name", models.CharField(max_length=150)),
                ("address_receiver_phone", models.CharField(max_length=11)),
                ("address_city_title", models.CharField(max_length=100)),
                ("address_province_title", models.CharField(max_length=100)),
                ("subtotal", models.DecimalField(decimal_places=0, max_digits=12)),
                ("shipping_cost", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "packaging_cost",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=255)),
                ("variant_info", models.CharField(blank=True, max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="products.productvariant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tracking_code"], name="orders_orde_trackin_252782_idx"
            ),
        ),
    ]
