# Generated by Django 6.0.7 on 2026-08-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0002_order_orderitem_order_orders_orde_user_id_0ae59f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("processing", "در حال پردازش"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل داده شده"),
                    ("cancelled", "لغو شده"),
                    ("expired", "منقضی شده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway", models.CharField(max_length=30)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "authority",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("ref_id", models.CharField(blank=True, max_length=100)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["authority"], name="orders_paym_authori_9e07d8_idx"
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="orders_paym_order_i_e3de73_idx",
                    ),
                ],
            },
        ),
    ]
