# Generated by Django 6.0.7 on 2026-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_refundrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
