# Generated by Django 6.0.7 on 2026-08-10 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_refundrequest_refund_amount"),
        (
            "products",
            "0005_productvariant_promo_end_productvariant_promo_price_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "درصدی"), ("fixed", "مبلغ ثابت")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="حداقل مبلغ سبد برای اعمال این کد؛ خالی یعنی بدون محدودیت.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="سقف کلی استفاده در کل سایت؛ خالی یعنی نامحدود.",
                        null=True,
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="سقف استفاده برای هر کاربر؛ خالی یعنی نامحدود.",
                        null=True,
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True, related_name="discount_codes", to="products.brand"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discount_codes",
                        to="products.category",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="discount_codes", to="products.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscountCodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="orders.discountcode",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_usages",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discount_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["code", "is_active"], name="orders_disc_code_db4727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountcodeusage",
            index=models.Index(
                fields=["code", "user"], name="orders_disc_code_id_222a10_idx"
            ),
        ),
    ]
