# Generated by Django 6.0.7 on 2026-08-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_discountcode_discountcodeusage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_in_carts",
                to="orders.discountcode",
            ),
        ),
    ]
