# Generated by Django 6.0.7 on 2026-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_cart_discount_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_code_str",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
