# Generated by Django 6.0.7 on 2026-07-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributevalue",
            options={
                "ordering": ["attribute", "value"],
                "verbose_name": "ویژگی محصول",
                "verbose_name_plural": "ویژگی محصولات",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
    ]
