# Generated by Django 6.0.7 on 2026-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_sales_count_productvariant_discount_price_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-sales_count"], name="products_pr_sales_c_6796bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["discount_price"], name="products_pr_discoun_697bc2_idx"
            ),
        ),
    ]
