# Generated by Django 6.0.7 on 2026-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_products_pr_sales_c_6796bf_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="promo_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="promo_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="promo_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "درصدی"), ("fixed", "مبلغ ثابت")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=0, max_digits=12)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="products.brand"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="products.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="products.product"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_at", "end_at", "is_active"],
                        name="products_ca_start_a_ad4c5f_idx",
                    )
                ],
            },
        ),
    ]
