# Generated by Django 6.0.7 on 2026-08-12 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_discount_amount_order_discount_code_str"),
        (
            "products",
            "0005_productvariant_promo_end_productvariant_promo_price_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="low_stock_alert_sent",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="خالی بگذارید تا مقدار پیش\u200cفرض سراسری (LOW_STOCK_THRESHOLD) استفاده شود.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RestockRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره موبایل باید با 09 شروع شود و 11 رقم باشد.",
                                regex="^09\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_notified", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restock_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_requests",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["variant", "is_notified"],
                        name="products_re_variant_ad0bd4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "خرید از تأمین\u200cکننده"),
                            ("sale", "فروش"),
                            ("return", "بازگشت سفارش"),
                            ("manual_adjustment", "تنظیم دستی"),
                            ("damage", "خرابی/دورریز"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(
                        help_text="مثبت = افزایش موجودی، منفی = کاهش موجودی"
                    ),
                ),
                ("stock_after", models.PositiveIntegerField(editable=False)),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="فقط برای ثبت دستی از پنل ادمین؛ برای رکوردهای خودکار خالی می\u200cماند.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "created_at"],
                        name="products_st_variant_793171_idx",
                    ),
                    models.Index(
                        fields=["movement_type"], name="products_st_movemen_3c3c44_idx"
                    ),
                ],
            },
        ),
    ]
