# Generated by Django 6.0.7 on 2026-09-25 07:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_ensure_product_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="توضیحات"
            ),
        ),
    ]
