# Generated by Django 6.0.7 on 2026-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="عنوان انگلیسی؛ در صورت پر بودن، اسلاگ از روی همین ساخته می\u200cشود.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="عنوان انگلیسی؛ در صورت پر بودن، اسلاگ از روی همین ساخته می\u200cشود.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="عنوان انگلیسی؛ در صورت پر بودن، اسلاگ از روی همین ساخته می\u200cشود.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="عنوان انگلیسی؛ در صورت پر بودن، اسلاگ از روی همین ساخته می\u200cشود.",
                max_length=255,
            ),
        ),
    ]
