# Generated by Django 6.0.7 on 2026-09-27 06:18

import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0011_brand_title_en_campaign_title_en_category_title_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_jpg",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="نسخه\u200cی خودکار JPG از image، مخصوص og:image.",
                null=True,
                upload_to=products.utils.product_image_jpg_upload_path,
            ),
        ),
    ]
